service: default
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
- url: /.*
  script: demo.main.app
  login: required
  secure: always

libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest
